import 'package:flutter/material.dart';
import 'package:flutterapp/storapp/generateddetailwidget1/generated/GeneratedGroup63Widget1.dart';
import 'package:flutterapp/storapp/generateddetailwidget1/generated/GeneratedGroup68Widget1.dart';
import 'package:flutterapp/storapp/generateddetailwidget1/generated/GeneratedGroup50Widget1.dart';
import 'package:flutterapp/storapp/generateddetailwidget1/generated/GeneratedRectangle26Widget1.dart';
import 'package:flutterapp/storapp/generateddetailwidget1/generated/GeneratedGroup48Widget1.dart';
import 'package:flutterapp/storapp/generateddetailwidget1/generated/GeneratedTakingtheclassiclookofheritageNikeRunningintoanewrealmt1.dart';
import 'package:flutterapp/storapp/generateddetailwidget1/generated/GeneratedRectangle30Widget3.dart';
import 'package:flutterapp/storapp/generateddetailwidget1/generated/GeneratedGroup79Widget2.dart';
import 'package:flutterapp/storapp/generateddetailwidget1/generated/GeneratedGroup65Widget1.dart';
import 'package:flutterapp/storapp/generateddetailwidget1/generated/GeneratedGroup84Widget1.dart';
import 'package:flutterapp/storapp/generateddetailwidget1/generated/GeneratedRectangle29Widget1.dart';

/* Frame Detail
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDetailWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(40.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(40.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(40.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -12.5,
                right: null,
                bottom: null,
                width: 375.0,
                height: 412.0,
                child: GeneratedRectangle29Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 349.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 463.0,
                child: GeneratedRectangle30Widget3(),
              ),
              Positioned(
                left: 24.0,
                top: 495.0,
                right: null,
                bottom: null,
                width: 196.0,
                height: 89.0,
                child: GeneratedGroup63Widget1(),
              ),
              Positioned(
                left: 32.0,
                top: 96.9052734375,
                right: null,
                bottom: null,
                width: 310.0,
                height: 227.810546875,
                child: GeneratedGroup48Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 700.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 112.0,
                child: GeneratedRectangle26Widget1(),
              ),
              Positioned(
                left: 24.0,
                top: 732.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 48.0,
                child: GeneratedGroup84Widget1(),
              ),
              Positioned(
                left: 162.0,
                top: 732.0,
                right: null,
                bottom: null,
                width: 187.0,
                height: 47.0,
                child: GeneratedGroup50Widget1(),
              ),
              Positioned(
                left: 26.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 323.0,
                height: 24.0,
                child: GeneratedGroup68Widget1(),
              ),
              Positioned(
                left: 24.0,
                top: 445.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 38.0,
                child:
                    GeneratedTakingtheclassiclookofheritageNikeRunningintoanewrealmt1(),
              ),
              Positioned(
                left: 24.0,
                top: 381.0,
                right: null,
                bottom: null,
                width: 324.0,
                height: 51.0,
                child: GeneratedGroup65Widget1(),
              ),
              Positioned(
                left: 24.0,
                top: 598.0,
                right: null,
                bottom: null,
                width: 323.0,
                height: 78.0,
                child: GeneratedGroup79Widget2(),
              )
            ]),
      ),
    ));
  }
}
