import 'package:flutter/material.dart';
import 'package:flutterapp/storapp/generatedberandawidget/generated/GeneratedGroup30Widget.dart';
import 'package:flutterapp/storapp/generatedberandawidget/generated/GeneratedGroup59Widget.dart';
import 'package:flutterapp/storapp/generatedberandawidget/generated/GeneratedGroup67Widget.dart';
import 'package:flutterapp/storapp/generatedberandawidget/generated/GeneratedEllipse19Widget.dart';
import 'package:flutterapp/storapp/generatedberandawidget/generated/Generated2Widget.dart';
import 'package:flutterapp/storapp/generatedberandawidget/generated/GeneratedRectangle35Widget.dart';
import 'package:flutterapp/storapp/generatedberandawidget/generated/GeneratedGroup69Widget.dart';
import 'package:flutterapp/storapp/generatedberandawidget/generated/GeneratedGroup33Widget.dart';

/* Component Beranda
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBerandaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(40.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(40.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(40.0),
                child: Container(
                  color: Color.fromARGB(255, 248, 248, 248),
                ),
              ),
              Positioned(
                left: 26.0,
                top: 106.0,
                right: null,
                bottom: null,
                width: 377.0,
                height: 244.0,
                child: GeneratedGroup33Widget(),
              ),
              Positioned(
                left: 26.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 324.0,
                height: 28.0,
                child: GeneratedGroup30Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 406.0,
                right: null,
                bottom: null,
                width: 324.8662109375,
                height: 445.0,
                child: GeneratedGroup69Widget(),
              ),
              Positioned(
                left: 26.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 323.0,
                height: 24.0,
                child: GeneratedGroup67Widget(),
              ),
              Positioned(
                left: 259.0,
                top: 735.0,
                right: null,
                bottom: null,
                width: 12.0,
                height: 12.0,
                child: GeneratedEllipse19Widget(),
              ),
              Positioned(
                left: 263.0,
                top: 736.0,
                right: null,
                bottom: null,
                width: 9.0,
                height: 15.0,
                child: Generated2Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 644.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 124.0,
                child: GeneratedRectangle35Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 699.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 113.0,
                child: GeneratedGroup59Widget(),
              )
            ]),
      ),
    ));
  }
}
