import 'package:flutter/material.dart';
import 'package:flutterapp/storapp/generatedonboardingwidget1/generated/GeneratedGroup4Widget1.dart';
import 'package:flutterapp/storapp/generatedonboardingwidget1/generated/GeneratedGetStartedWidget1.dart';
import 'package:flutterapp/storapp/generatedonboardingwidget1/generated/GeneratedLiveyourperfectWidget1.dart';
import 'package:flutterapp/storapp/generatedonboardingwidget1/generated/GeneratedVectorWidget1.dart';
import 'package:flutterapp/storapp/generatedonboardingwidget1/generated/GeneratedSmartgorgeousfashionablecollectionmakesyoucoolWidget1.dart';
import 'package:flutterapp/storapp/generatedonboardingwidget1/generated/GeneratedFrame14Widget1.dart';
import 'package:flutterapp/storapp/generatedonboardingwidget1/generated/GeneratedEllipse5Widget1.dart';

/* Frame On Boarding
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOnBoardingWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(40.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(40.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(40.0),
                child: Container(
                  color: Color.fromARGB(255, 34, 36, 51),
                ),
              ),
              Positioned(
                left: -53.0,
                top: 637.0,
                right: null,
                bottom: null,
                width: 486.0,
                height: 486.0,
                child: GeneratedEllipse5Widget1(),
              ),
              Positioned(
                left: 30.0,
                top: 93.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 595.0446166992188,
                child: GeneratedVectorWidget1(),
              ),
              Positioned(
                left: 142.0,
                top: 750.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 21.0,
                child: GeneratedGetStartedWidget1(),
              ),
              Positioned(
                left: -55.0,
                top: -25.0,
                right: null,
                bottom: null,
                width: 457.9189147949219,
                height: 474.485107421875,
                child: GeneratedGroup4Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 480.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 118.0,
                child: GeneratedLiveyourperfectWidget1(),
              ),
              Positioned(
                left: 36.0,
                top: 610.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 44.0,
                child:
                    GeneratedSmartgorgeousfashionablecollectionmakesyoucoolWidget1(),
              ),
              Positioned(
                left: 178.0,
                top: 724.0,
                right: null,
                bottom: null,
                width: 18.0,
                height: 18.0,
                child: GeneratedFrame14Widget1(),
              )
            ]),
      ),
    ));
  }
}
