import 'package:flutter/material.dart';
import 'package:flutterapp/storapp/generatedonboardingwidget/generated/GeneratedGetStartedWidget.dart';
import 'package:flutterapp/storapp/generatedonboardingwidget/generated/GeneratedLiveyourperfectWidget.dart';
import 'package:flutterapp/storapp/generatedonboardingwidget/generated/GeneratedEllipse5Widget.dart';
import 'package:flutterapp/storapp/generatedonboardingwidget/generated/GeneratedVectorWidget.dart';
import 'package:flutterapp/storapp/generatedonboardingwidget/generated/GeneratedFrame14Widget.dart';
import 'package:flutterapp/storapp/generatedonboardingwidget/generated/GeneratedSmartgorgeousfashionablecollectionmakesyoucoolWidget.dart';
import 'package:flutterapp/storapp/generatedonboardingwidget/generated/GeneratedGroup4Widget.dart';

/* Component On Boarding
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOnBoardingWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(40.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(40.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(40.0),
                child: Container(
                  color: Color.fromARGB(255, 39, 35, 32),
                ),
              ),
              Positioned(
                left: -53.0,
                top: 637.0,
                right: null,
                bottom: null,
                width: 486.0,
                height: 486.0,
                child: GeneratedEllipse5Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 93.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 595.0446166992188,
                child: GeneratedVectorWidget(),
              ),
              Positioned(
                left: 142.0,
                top: 750.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 21.0,
                child: GeneratedGetStartedWidget(),
              ),
              Positioned(
                left: -55.0,
                top: -25.0,
                right: null,
                bottom: null,
                width: 457.9189147949219,
                height: 474.485107421875,
                child: GeneratedGroup4Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 480.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 118.0,
                child: GeneratedLiveyourperfectWidget(),
              ),
              Positioned(
                left: 36.0,
                top: 610.0,
                right: null,
                bottom: null,
                width: 305.0,
                height: 44.0,
                child:
                    GeneratedSmartgorgeousfashionablecollectionmakesyoucoolWidget(),
              ),
              Positioned(
                left: 178.0,
                top: 724.0,
                right: null,
                bottom: null,
                width: 18.0,
                height: 18.0,
                child: GeneratedFrame14Widget(),
              )
            ]),
      ),
    ));
  }
}
