import 'package:flutter/material.dart';
import 'package:flutterapp/storapp/generatedmaskgroupwidget/generated/GeneratedDetailWidget.dart';

/* Group Mask group
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMaskgroupWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 812.0,
              child: GeneratedDetailWidget(),
            )
          ]),
    ));
  }
}
